"""empty message

Revision ID: 4e8b2f96b4ed
Revises: e81fdafd0ef4
Create Date: 2019-04-06 13:30:59.982852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4e8b2f96b4ed'
down_revision = 'e81fdafd0ef4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('excursion', sa.Column('city', sa.String(length=100), nullable=True))
    op.add_column('excursion', sa.Column('number', sa.Integer(), nullable=True))
    op.add_column('excursion', sa.Column('pt', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('excursion', 'pt')
    op.drop_column('excursion', 'number')
    op.drop_column('excursion', 'city')
    # ### end Alembic commands ###
