"""empty message

Revision ID: 4ff84ca403dc
Revises: 4e8b2f96b4ed
Create Date: 2019-05-08 16:03:18.709353

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ff84ca403dc'
down_revision = '4e8b2f96b4ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audio_excursion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('password_hash', sa.String(length=400), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('excursion_name', sa.String(length=200), nullable=True),
    sa.Column('excursion_description', sa.String(length=500), nullable=True),
    sa.Column('number', sa.Integer(), nullable=True),
    sa.Column('contacts', sa.String(length=400), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('pt', sa.String(length=100), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audio_excursion')
    # ### end Alembic commands ###
