"""empty message

Revision ID: e81fdafd0ef4
Revises: 
Create Date: 2019-04-03 20:41:28.761995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e81fdafd0ef4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('excursion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(length=300), nullable=True),
    sa.Column('date', sa.DateTime(), nullable=True),
    sa.Column('password_hash', sa.String(length=400), nullable=True),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('excursion_name', sa.String(length=200), nullable=True),
    sa.Column('excursion_description', sa.String(length=1500), nullable=True),
    sa.Column('excursion_duration', sa.String(length=20), nullable=True),
    sa.Column('place_description', sa.String(length=500), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('sile', sa.String(length=8), nullable=True),
    sa.Column('telephone_number', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('excursion')
    # ### end Alembic commands ###
